### PR TITLE
Add ffmpeg in webgl editor

### PR DESCRIPTION
**Pull request by webbertakken**
#### Changes

- This adds ffmpeg in webgl builds of the editor image.
- Closes https://github.com/game-ci/unity-builder/issues/223

#### Pending:

- [x] Confirmation that this is WebGL only
- [x] Confirmation that recommends are not necessary

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [X] Readme (updated or not needed)

### CODE REVIEW

**Comment by mob-sakai** [comment]
LGTM

**Comment by mob-sakai** [comment]
We should add an audio clip to `Resources` in the test project.

**Review by GabLeRoux — APPROVED** [review]

**Comment by mob-sakai** [comment]
I added CC0 licensed audio assets (from https://opengameart.org) to the test project.
- 8bit Bossa.mp3
- vgdeathsound.wav
- vgmenuselect.ogg

If possible, all formats (supported) should be added.
https://docs.unity3d.com/Manual/AudioFiles.html

**Comment by GabLeRoux** [comment]
I found quite a few audio file formats here:
https://docs.espressif.com/projects/esp-adf/en/latest/design-guide/audio-samples.html

but they're CC3 so we would have to give credit. Maybe we can use some of the files you found and convert them to other formats using something like [Audacity](https://www.audacityteam.org/download/)

**Comment by mob-sakai** [comment]
@GabLeRoux 
Thanks.
I reformatted the asset.
- vgdeathsound_wav.wav
- vgdeathsound_ogg.ogg
- vgdeathsound_mp3.mp3
- vgdeathsound_aiff.aiff

**Review by mob-sakai — DISMISSED** [review]

**Comment by mob-sakai** [comment]
https://github.com/game-ci/docker/pull/89/checks?check_run_id=2019308643#step:14:2248
>Errors during import of AudioClip Assets/Resources/vgdeathsound_wav.wav:
ffmpeg -i "Temp/fsbankcache/tmpinput_6M9gmr.WAV" -f mp4 -codec aac -b:a 192000 -strict experimental -y "Temp/importedAudioTempPrimary"
FSBTool ERROR: Error converting Temp/fsbankcache/tmpinput_6M9gmr.WAV: make sure you have avconv or ffmpeg installed
FSBTool ERROR: Failed encoding audio clip '/github/workspace/reference-project-test/Assets/Resources/vgdeathsound_wav.wav' to AAC. Possibly the file is too short. Try to append silence such that the length becomes greater than 256 samples.

Hmmm.
Oddly enough, it contains more than 256 samples.

image

**Comment by johanhelsing** [comment]
> Confirmation that this is WebGL only

Can confirm this is the case for me. The WebGL build is broken, but the corresponding Windows build works.

**Comment by mob-sakai** [comment]
I've reverted the "asset import test" commit.
I'm going to create another PR.

**Pull request merged**
