### PR TITLE
chore: phase out old workflow tags

### PR DESCRIPTION
**Pull request by webbertakken**
#### Changes

- For base and hub images we build for all base platforms at the same time, tags are shared
- For legacy and specific version editor workflows we keep them separated, so that we can manage workflows for different baseOses separately.

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [ ] Readme (updated or not needed)

### CODE REVIEW

**Comment by webbertakken** [comment]
Found a potential blocker for windows builds:

image

@AndrewKahr these builds ran before right?

**Comment by AndrewKahr** [comment]
I think this might be the first time the windows ones were attempted. I thought they would run with the original PR but it appears that was not the case. I believe it's complaining about using the registry container for the builds. I might be able to just remove it and have it build locally.

**Comment by AndrewKahr** [comment]
@webbertakken Is there a specific reason for using a local registry container vs just building locally on the runner?

**Comment by webbertakken** [comment]
It looks like windows images are not supported [at all](https://github.com/actions/runner/issues/904)?

Hopefully there is some kind of workaround - I think we don't necessarily need GitHub support, just the build to work would go a long way.

**Comment by AndrewKahr** [comment]
Yea that's what I've been seeing. I'm gonna put up a commit that removes reliance on the container registry and just have it build locally on the runner. I think the main purpose of the PR workflow is to make sure it builds so I don't see an issue with this as a workaround.

**Comment by webbertakken** [comment]
Ok. In the meantime I'm going to merge this. Could you reference this PR in your commit please?

**Pull request merged**
