### PR TITLE
Test PR workflow from `main` branch

### PR DESCRIPTION
**Pull request by webbertakken**
Just testing if the test workflow for PRs from `main` branch now works.

### CODE REVIEW

**Comment by webbertakken** [comment]
Found the next error:

image

**Comment by webbertakken** [comment]
FYI: @AndrewKahr

**Comment by AndrewKahr** [comment]
I'm a little confused, I removed the --push as well as the localhost references but they seem to be back after the rebase. Did I do something wrong?

**Comment by webbertakken** [comment]
All green 
image

**Pull request closed without merging**
