### PR TITLE
Add test for alpha/beta Unity versions

### PR DESCRIPTION
**Pull request by mob-sakai**
#### Changes

- Add test for `2021.1.0bx`
  - Check for libraries to be added in the future release

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [x] Readme (updated or not needed)

### CODE REVIEW

**Comment by mob-sakai** [comment]
Sorry, I made a mistake.

**Comment by webbertakken** [comment]
Mistake of opening or of closing? In case the closing was the mistake, I've reopened it for you, otherwise feel free to close again.

**Comment by mob-sakai** [comment]
Thanks.
I've created this PR for alpha/beta version support (#50).

**Comment by mob-sakai** [comment]
Should I exclude commits that add `lld`? (21d1e89)

**Comment by webbertakken** [comment]
Is `lld` a strict requirement for `2021.x-linux-il2cpp`?

If so, lets keep it.

**Comment by jsteinich** [comment]
Since 2021.1 has been out for a bit, it would be good to at least get the `lld` change merged in.

**Comment by webbertakken** [comment]
> Since 2021.1 has been out for a bit, it would be good to at least get the `lld` change merged in.

Good idea. Feel free to add it in a separate PR.

**Comment by webbertakken** [comment]
Reference #104

**Review by lastthyme — APPROVED** [review]

**Pull request closed without merging**
