### PR TITLE
fix: add extra dependencies for webgl and il2cpp

### LINKED ISSUE #53: Building for il2cpp StandaloneLinux64 and webgl fails with 'Could not find valid clang executable at clang'
Linking the following gitlab issue which has more details:  
https://gitlab.com/gableroux/unity3d-gitlab-ci-example/-/issues/139

I think this needs to be solved in here, but I don't have any clue on what to do. Help is greatly appreciated.

### PR DESCRIPTION
**Pull request by mob-sakai**
#### Changes

- Fix #53 
- Add dependencies for `webgl` and `linux-il2cpp`
  - python
  - build-essential
  - clang
 
#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [ ] Readme (updated or not needed)

#### Versions and modules to be fixed

Tested with #60 (in my repo)

| version | WebGL | IL2CPP |
| -- | -- | -- |
| 2018.3.x | ✅  | ✅ |
| 2018.4.x | ✅  | ✅ |
| 2019.1.x | ✅ <br>(With #59) | ✅ |
| 2019.2.x | ✅  | ✅ |
| 2019.3.x | ✅  | ❌ |
| 2019.4.x | ✅  | ✅ |
| 2020.1.x | ✅  | ✅ |
| 2020.2.x | ✅  | ✅ |
| 2021.1.x | ✅  | ❌ |

### CODE REVIEW

**Comment by webbertakken** [comment]
Nice work @mob-sakai 

How much size does this add to the image without install recommends?

If it's relatively little we might add it to the base image as discussed in #53

**Comment by mob-sakai** [comment]
@webbertakken 
About 340MB.

```
REPOSITORY   TAG       IMAGE ID       CREATED              SIZE
editor       after     bf3c52bbd759   1 second ago         6.38GB
editor       before    e0a43d920df0   About a minute ago   6.04GB
```

Test:

```dockerfile
FROM unityci/editor:2019.4.18f1-webgl-0

RUN apt-get -q update \
  && apt-get -q install -y --no-install-recommends --allow-downgrades \
    python \
    build-essential \
    clang \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
```

**Comment by webbertakken** [comment]
Nice work!

**Comment by webbertakken** [comment]
@mob-sakai Do you think this fix is applicable for https://github.com/game-ci/unity-builder/issues/143#issuecomment-730680324 (android il2cpp and ios-il2cpp)?

**Comment by mob-sakai** [comment]
@webbertakken 
Maybe.
I'll test it later.

**Comment by mob-sakai** [comment]
@webbertakken
In my tests, `android-il2cpp` and `ios-il2cpp` built the project successfully with `main` branch.
No additional fixes are required

NOTE: In 2018.3 or later, `ios` uses il2cpp script backend by default for building.

**Comment by mob-sakai** [comment]
@webbertakken 
Should I add `android-il2cpp` to test workflow?

**Comment by webbertakken** [comment]
I think @davidmfinol is more qualified to answer this. It seems that there are cases (maybe all) where Android IL2CPP already works as well.

**Pull request merged**
